# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminName', models.CharField(max_length=100)),
                ('AdminID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='LoginId',
        ),
        migrations.AddField(
            model_name='login',
            name='Role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('employee', 'EMPLOYEE'), ('manager', 'MANAGER')], default='admin', max_length=20),
        ),
    ]
