# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20170822_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
                ('EmployeeId', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
