# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_addemployeedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMachines',
            new_name='AddMachine',
        ),
    ]
