# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20170822_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddAMCWarranty',
            new_name='AddAMC',
        ),
    ]
